# Generated by stubgen-pyx from asynch/cursors.pyx
import logging
from collections import namedtuple
from typing import Any, Self

Column = namedtuple("Column", "name type_code display_size internal_size precision scale null_ok")
logger = logging.getLogger(__name__)

class Cursor:
    def __init__(self, connection=None, echo=False): ...
    def __repr__(self): ...
    @property
    def connection(self):
        """This read-only attribute return a reference to the Connection
        object on which the cursor was created."""
    @property
    def rowcount(self):
        """
        :return: the number of rows that the last .execute*() produced.
        """
    @property
    def status(self):
        """Return the status of the cursor.

        :return: the Cursor object status
        :rtype: str (CursorStatus StrEnum)
        """
    @property
    def arraysize(self):
        """Number of rows `fetchmany` returns when called without a size."""
    @arraysize.setter
    def arraysize(self, value): ...
    def setinputsizes(self, *args):
        """Does nothing, required by DB API."""
    def setoutputsizes(self, *args):
        """Does nothing, required by DB API."""
    async def cancel(self):
        """Ask the server to stop the query this cursor is running.

        Call it from another task than the one awaiting `execute`; the
        connection is drained and remains usable.

        :return: True if a query was cancelled
        """
    async def close(self) -> None: ...
    async def execute(self, query: str, args=None, context=None) -> int: ...
    async def executemany(self, query, args=None, context=None) -> int: ...
    async def fetchone(self) -> Any: ...
    async def fetchmany(self, size) -> list[Any]: ...
    async def fetchall(self) -> list[Any]: ...
    def make_external_tables(self, dialect, execution_options): ...
    def __aiter__(self): ...
    async def __anext__(self): ...
    async def __aexit__(self, exc_type, exc_val, exc_tb): ...
    async def __aenter__(self) -> Self: ...
    @property
    def description(self): ...
    def set_stream_results(self, stream_results, max_row_buffer):
        """
        Toggles results streaming from server. Driver will consume
        block-by-block of `max_row_buffer` size and yield row-by-row from each
        block.

        :param stream_results: enable or disable results streaming.
        :param max_row_buffer: specifies the maximum number of rows to buffer
               at a time.
        :return: None
        """
    def set_settings(self, settings):
        """
        Specifies settings for cursor.

        :param settings: dictionary of query settings
        :return: None
        """
    def set_types_check(self, types_check):
        """
        Toggles type checking for sequence of INSERT parameters.
        Disabled by default.

        :param types_check: new types check value.
        :return: None
        """
    def set_external_table(self, name, structure, data):
        """
        Adds external table to cursor context.

        If the same table is specified more than once the last one is used.

        :param name: name of external table
        :param structure: list of tuples (name, type) that defines table
                          structure. Example [(x, 'Int32')].
        :param data: sequence of rows of tuples or dicts for transmission.
        :return: None
        """
    def set_query_id(self, query_id=""):
        """
        Specifies the query identifier for cursor.

        :param query_id: the query identifier.
        :return: None
        """

class DictCursor(Cursor):
    async def fetchone(self) -> Any:
        """Fetch exactly one row from the last executed query.

        :raises AttributeError: columns mismatch

        :return: one row from the query
        :rtype: dict
        """
    async def fetchmany(self, size) -> list[Any]:
        """Fetch no more than `size` rows from the last executed query.

        :param size Optional[int]: fetch upt to the `size` entries or self._arraysize if None

        :raises AttributeError: columns mismatch

        :return: the list of rows from the query
        :rtype: list[dict]
        """
    async def fetchall(self) -> list[Any]:
        """Fetch all resulting rows from the last executed query.

        :raises AttributeError: columns mismatch

        :return: the list of all possible rows from the query
        :rtype: list[dict]
        """
