# Generated by stubgen-pyx from asynch/proto/columns/__init__.pyx

column_by_type: dict
aliases = [
    ("Point", "Tuple(Float64, Float64)"),
    ("Ring", "Array(Point)"),
    ("Polygon", "Array(Ring)"),
    ("MultiPolygon", "Array(Polygon)"),
]

def get_column_by_spec(spec, column_options): ...
async def read_column(reader, writer, context, column_spec, n_items): ...
async def write_column(
    reader, writer, context, column_name, column_spec, items, types_check=False
): ...
