# Generated by stubgen-pyx from asynch/proto/columns/arraycolumn.pyx

from struct import Struct

from .base import Column

class ArrayColumn(Column):
    """
    Nested arrays written in flatten form after information about their
    sizes (offsets really).
    One element of array of arrays can be represented as tree:
    (0 depth)          [[3, 4], [5, 6]]
                      |               |
    (1 depth)      [3, 4]           [5, 6]
                   |    |           |    |
    (leaf)        3     4          5     6

    Offsets (sizes) written in breadth-first search order. In example above
    following sequence of offset will be written: 4 -> 2 -> 4
    1) size of whole array: 4
    2) size of array 1 in depth=1: 2
    3) size of array 2 plus size of all array before in depth=1: 2 + 2 = 4

    After sizes info comes flatten data: 3 -> 4 -> 5 -> 6
    """

    py_types: tuple[type, ...] | None
    size_struct = Struct("<Q")

    def __init__(self, nested_column, **kwargs): ...
    def size_pack(self, value): ...
    async def size_unpack(self): ...
    async def write_items(self, items): ...
    async def write_data(self, data): ...
    async def read_data(self, rows): ...
    async def read_state_prefix(self): ...
    async def write_state_prefix(self): ...

def create_array_column(spec, column_by_spec_getter, column_options): ...
