# Generated by stubgen-pyx from asynch/proto/columns/boolcolumn.pyx

from asynch.proto.columns.base import FormatColumn

class BoolColumn(FormatColumn):
    ch_type = "Bool"
    py_types: tuple[type, ...] | None
    format = "?"
