# Generated by stubgen-pyx from asynch/proto/columns/datecolumn.pyx

from datetime import date

from .base import FormatColumn

epoch_start = date(1970, 1, 1)
epoch_end = date(2149, 6, 6)
epoch_start_date32 = date(1900, 1, 1)
epoch_end_date32 = date(2299, 12, 31)
lazy_date_lut: LazyLUT
lazy_date_lut_reverse: LazyLUT

class LazyLUT(dict):
    def __init__(self, *args, _factory, **kwargs): ...
    def __missing__(self, key): ...

class DateColumn(FormatColumn):
    ch_type = "Date"
    py_types: tuple[type, ...] | None
    format = "H"
    min_value = epoch_start
    max_value = epoch_end
    date_lut = lazy_date_lut
    date_lut_reverse = lazy_date_lut_reverse

    def before_write_items(self, items, nulls_map=None): ...
    def after_read_items(self, items, nulls_map=None): ...

class Date32Column(DateColumn):
    ch_type = "Date32"
    format = "i"
    min_value = epoch_start_date32
    max_value = epoch_end_date32
    date_lut = lazy_date_lut
    date_lut_reverse = lazy_date_lut_reverse
