# Generated by stubgen-pyx from asynch/proto/columns/datetimecolumn.pyx

from datetime import UTC

from .base import FormatColumn

utc = UTC

class DateTimeColumn(FormatColumn):
    ch_type = "DateTime"
    py_types: tuple[type, ...] | None
    format = "I"

    def __init__(self, timezone=None, offset_naive=True, **kwargs): ...
    def after_read_items(self, items, nulls_map=None): ...
    def before_write_items(self, items, nulls_map=None): ...

class DateTime64Column(DateTimeColumn):
    ch_type = "DateTime64"
    format = "q"
    max_scale = 6

    def __init__(self, scale=0, **kwargs): ...
    def after_read_items(self, items, nulls_map=None): ...
    def before_write_items(self, items, nulls_map=None): ...

def get_timezone(tz_name): ...
def create_datetime_column(spec, column_options): ...
