# Generated by stubgen-pyx from asynch/proto/columns/decimalcolumn.pyx

from .base import FormatColumn
from .intcolumn import Int128Column, Int256Column

class DecimalColumn(FormatColumn):
    py_types: tuple[type, ...] | None
    max_precision = None

    def __init__(self, precision, scale, types_check=False, **kwargs): ...
    def after_read_items(self, items, nulls_map=None): ...
    def before_write_items(self, items, nulls_map=None): ...

class Decimal32Column(DecimalColumn):
    format = "i"
    max_precision = 9
    int_size = 4

class Decimal64Column(DecimalColumn):
    format = "q"
    max_precision = 18
    int_size = 8

class Decimal128Column(DecimalColumn, Int128Column):
    max_precision = 38

class Decimal256Column(DecimalColumn, Int256Column):
    max_precision = 76

def create_decimal_column(spec, column_options): ...
