# Generated by stubgen-pyx from asynch/proto/columns/dynamiccolumn.pyx

"""Reader for ClickHouse's Dynamic / Variant column families.

These are not user-facing types yet: they exist so the JSON column can be
composed out of them instead of hand-rolling Variant deserialization. The
byte layout mirrors `SerializationDynamic` and `SerializationVariant`.
"""

from .base import Column

DYNAMIC_V1 = 1
DYNAMIC_V2 = 2
VARIANT_MODE_BASIC = 0
VARIANT_MODE_COMPACT = 1
NULL_DISCRIMINATOR = 255
SHARED_VARIANT_NAME = "SharedVariant"

class DynamicColumn(Column):
    """A ClickHouse `Dynamic` column.

    The variant types are not known at construction: they arrive on the wire
    in `read_state_prefix`. The list always ends with an implicit
    `SharedVariant` - a byte string carrying `encodeDataType +
    serializeBinary` blobs - which catches values whose type matches none of
    the declared variants.
    """

    py_types: tuple[type, ...] | None

    def __init__(self, column_by_spec_getter, shared_value_decoder=None, **kwargs): ...
    async def read_state_prefix(self): ...
    async def read_items(self, n_items): ...

class SharedValueDecoder:
    """Decoder for the `encodeDataType + serializeBinary` payloads carried by
    a SharedVariant's underlying byte-string column.

    One instance per block: the column cache then accumulates across every
    overflow value, both the JSON column's own shared paths and those of
    every nested Dynamic column.
    """
    def __init__(self, column_by_spec_getter): ...
    async def decode(self, blob):
        """Decode one shared value; returns the Python object it encodes.

        Async because the column readers are: nothing here touches the
        socket, the reader is the in-memory blob.
        """

def create_dynamic_column(spec, column_by_spec_getter, column_options): ...
