# Generated by stubgen-pyx from asynch/proto/columns/enumcolumn.pyx

from .intcolumn import IntColumn

class EnumColumn(IntColumn):
    py_types: tuple[type, ...] | None

    def __init__(self, enum_cls, **kwargs): ...
    def before_write_items(self, items, nulls_map=None): ...
    def after_read_items(self, items, nulls_map=None): ...

class Enum8Column(EnumColumn):
    ch_type = "Enum8"
    format = "b"
    int_size = 1

class Enum16Column(EnumColumn):
    ch_type = "Enum16"
    format = "h"
    int_size = 2

def create_enum_column(spec, column_options): ...
