# Generated by stubgen-pyx from asynch/proto/columns/floatcolumn.pyx

from .base import FormatColumn

class FloatColumn(FormatColumn):
    py_types: tuple[type, ...] | None

class Float32(FloatColumn):
    ch_type = "Float32"
    format = "f"

    def __init__(self, types_check=False, **kwargs): ...

class Float64(FloatColumn):
    ch_type = "Float64"
    format = "d"
