# Generated by stubgen-pyx from asynch/proto/columns/intcolumn.pyx

from .base import FormatColumn

class IntColumn(FormatColumn):
    py_types: tuple[type, ...] | None
    int_size = None

    def __init__(self, types_check=False, **kwargs): ...

class UIntColumn(IntColumn):
    def __init__(self, types_check=False, **kwargs): ...

class Int8Column(IntColumn):
    ch_type = "Int8"
    format = "b"
    int_size = 1

class Int16Column(IntColumn):
    ch_type = "Int16"
    format = "h"
    int_size = 2

class Int32Column(IntColumn):
    ch_type = "Int32"
    format = "i"
    int_size = 4

class Int64Column(IntColumn):
    ch_type = "Int64"
    format = "q"
    int_size = 8

class UInt8Column(UIntColumn):
    ch_type = "UInt8"
    format = "B"
    int_size = 1

class UInt16Column(UIntColumn):
    ch_type = "UInt16"
    format = "H"
    int_size = 2

class UInt32Column(UIntColumn):
    ch_type = "UInt32"
    format = "I"
    int_size = 4

class UInt64Column(UIntColumn):
    ch_type = "UInt64"
    format = "Q"
    int_size = 8

class BigIntColumn(IntColumn):
    async def write_items(self, items): ...
    async def read_items(self, n_items): ...

class BigUIntColumn(UIntColumn):
    async def write_items(self, items): ...
    async def read_items(self, n_items): ...

class Int128Column(BigIntColumn):
    ch_type = "Int128"
    int_size = 16

class Int256Column(BigIntColumn):
    ch_type = "Int256"
    int_size = 32

class UInt128Column(BigUIntColumn):
    ch_type = "UInt128"
    int_size = 16

class UInt256Column(BigUIntColumn):
    ch_type = "UInt256"
    int_size = 32
