# Generated by stubgen-pyx from asynch/proto/columns/ipcolumn.pyx

from .intcolumn import UInt32Column
from .stringcolumn import ByteFixedString

class IPv4Column(UInt32Column):
    ch_type = "IPv4"
    py_types: tuple[type, ...] | None

    def __init__(self, types_check=False, **kwargs): ...
    def after_read_items(self, items, nulls_map=None): ...
    def before_write_items(self, items, nulls_map=None): ...

class IPv6Column(ByteFixedString):
    ch_type = "IPv6"
    py_types: tuple[type, ...] | None

    def __init__(self, reader, writer, types_check=False, **kwargs): ...
    def after_read_items(self, items, nulls_map=None): ...
    def before_write_items(self, items, nulls_map=None): ...
