# Generated by stubgen-pyx from asynch/proto/columns/jsoncolumn.pyx

"""ClickHouse `JSON` column (and the legacy `Object('json')` spelling).

The wire format is the one introduced in 24.8 and stabilised in 25.x. Both
directions are composed out of existing column readers rather than
hand-rolled: `DynamicColumn` reads one dynamic path's body, and the shared
sub-column is an `Array(Tuple(String, String))`.
"""

from .base import Column

OBJECT_V1 = 0
OBJECT_STRING = 1
OBJECT_V2 = 2

class JsonColumn(Column):
    """Reads a JSON column into nested dicts; writes dicts or JSON text.

    Reading covers V1/V2 framing and the string fallback. Writing emits V2,
    which the server downgrades by itself when the client revision is older.
    """

    py_types: tuple[type, ...] | None
    null_value = {}
    prefix_needs_items = True

    def __init__(self, column_by_spec_getter, **kwargs): ...
    async def read_state_prefix(self): ...
    async def read_items(self, n_items): ...
    async def write_state_prefix(self, items=None): ...
    async def write_items(self, items): ...

class LegacyJsonColumn(Column):
    """The pre-24.8 `Object('json')` layout.

    Servers from 24.8 onwards removed the type entirely, so this only matters
    when talking to an older one; its framing (UInt8 version, then a type
    spec string) is incompatible with the `JSON` format above.
    """

    py_types: tuple[type, ...] | None
    null_value = {}

    def __init__(self, column_by_spec_getter, **kwargs): ...
    async def write_state_prefix(self): ...
    async def read_items(self, n_items): ...
    async def write_items(self, items): ...

def create_json_column(spec, column_by_spec_getter, column_options): ...
