# Generated by stubgen-pyx from asynch/proto/columns/lowcardinalitycolumn.pyx

from .base import Column
from .intcolumn import UInt8Column, UInt16Column, UInt32Column, UInt64Column

class LowCardinalityColumn(Column):
    """
    Stores column as index (unique elements) and keys.
    Good for de-duplication of large values with low cardinality.
    """

    int_types = {0: UInt8Column, 1: UInt16Column, 2: UInt32Column, 3: UInt64Column}
    has_additional_keys_bit = 1 << 9
    need_update_dictionary = 1 << 10
    serialization_type: int

    def __init__(self, nested_column, **kwargs): ...
    async def read_state_prefix(self): ...
    async def write_state_prefix(self): ...

def create_low_cardinality_column(spec, column_by_spec_getter, column_options): ...
