# Generated by stubgen-pyx from asynch/proto/columns/nothingcolumn.pyx

from .intcolumn import FormatColumn

class NothingColumn(FormatColumn):
    ch_type = "Nothing"
    format = "B"

    @property
    def size(self): ...
    def after_read_items(self, items, nulls_map=None): ...
