# Generated by stubgen-pyx from asynch/proto/columns/nullcolumn.pyx

from .intcolumn import FormatColumn

class NullColumn(FormatColumn):
    ch_type = "Null"
    format = "B"

    @property
    def size(self): ...
    def after_read_items(self, items, nulls_map=None): ...
