# Generated by stubgen-pyx from asynch/proto/columns/stringcolumn.pyx

from asynch.proto.columns.base import Column

class String(Column):
    ch_type = "String"
    py_types: tuple[type, ...] | None
    null_value = ""
    read_as_bytes = False

    async def write_items(self, items): ...
    async def read_items(self, n_items): ...

class ByteString(String):
    py_types: tuple[type, ...] | None
    null_value = b""
    read_as_bytes = True

class FixedString(String):
    ch_type = "FixedString"
    read_as_bytes = False

    def __init__(self, reader, writer, length, **kwargs): ...
    async def write_items(self, items): ...
    async def read_items(self, n_items): ...

class ByteFixedString(FixedString):
    py_types: tuple[type, ...] | None
    null_value = b""
    read_as_bytes = True

def create_string_column(spec, column_options): ...
