# Generated by stubgen-pyx from asynch/proto/connection.pyx
import logging
from typing import Any

from asynch.proto import constants

logger = logging.getLogger(__name__)

class QueryProcessingStage:
    """Determines till which state SELECT query should be executed."""

    FETCH_COLUMNS = 0
    WITH_MERGEABLE_STATE = 1
    COMPLETE = 2

class Packet:
    def __init__(self): ...

class Connection:
    # Resolved (host, port) candidates, including alt_hosts; the port
    # is filled in from the scheme when the caller did not give one.
    hosts: list[tuple[str, int]]
    log_priorities = (
        "Unknown",
        "Fatal",
        "Critical",
        "Error",
        "Warning",
        "Notice",
        "Information",
        "Debug",
        "Trace",
    )

    def __init__(
        self,
        user=constants.DEFAULT_USER,
        password=constants.DEFAULT_PASSWORD,
        host=constants.DEFAULT_HOST,
        port=None,
        database=constants.DEFAULT_DATABASE,
        client_name=constants.CLIENT_NAME,
        connect_timeout=constants.DBMS_DEFAULT_CONNECT_TIMEOUT_SEC,
        send_receive_timeout=constants.DBMS_DEFAULT_TIMEOUT_SEC,
        sync_request_timeout=constants.DBMS_DEFAULT_SYNC_REQUEST_TIMEOUT_SEC,
        compress_block_size=constants.DEFAULT_COMPRESS_BLOCK_SIZE,
        compression=False,
        secure=False,
        verify=True,
        ssl_version=None,
        ca_certs=None,
        ciphers=None,
        alt_hosts=None,
        stack_track=False,
        settings_is_important=False,
        **kwargs,
    ): ...
    def get_block_reader(self): ...
    def get_block_writer(self): ...
    async def send_hello(self): ...
    def get_server(self): ...
    def unexpected_packet_message(self, expected, packet_type): ...
    async def receive_hello(self): ...
    async def ping(self) -> bool: ...
    async def receive_data(self, raw=False): ...
    async def receive_exception(self): ...
    async def read_exception(self, additional_message=None): ...
    async def receive_profile_info(self): ...
    async def receive_multistring_message(self, packet_type): ...
    def log_block(self, block): ...
    async def receive_packet(self): ...
    async def packet_generator(self): ...
    async def receive_result(self, with_column_types=False, progress=False, columnar=False): ...
    async def receive_progress(self): ...
    async def send_cancel(self): ...
    async def cancel(self):
        """Ask the server to stop the running query.

        Only the cancel packet is sent: the task awaiting the query owns the
        read side of the socket, and reading from here too would interleave
        two readers on one stream. The server answers a cancel by ending the
        stream, so that task drains the packets already in flight and returns
        the rows it received - the connection is left at a packet boundary and
        stays usable.

        Safe to call when no query is running; it then does nothing.

        :return: True if a cancel was sent
        """
    async def send_query(self, query, query_id=""): ...
    def reset_state(self): ...
    async def disconnect(self) -> None: ...
    async def connect(self) -> None: ...
    async def execute(
        self,
        query,
        args=None,
        with_column_types=False,
        external_tables=None,
        query_id="",
        settings=None,
        types_check=False,
        columnar=False,
    ) -> Any:
        """
        Executes query.

        Establishes new connection if it wasn't established yet.
        After query execution connection remains intact for next queries.
        If connection can't be reused it will be closed and new connection will
        be created.

        :param query: query that will be send to server.
        :param args: substitution parameters for SELECT queries and data for
                       INSERT queries. Data for INSERT can be `list`, `tuple`
                       or :data:`~types.GeneratorType`.
                       Defaults to ``None`` (no parameters  or data).
        :param with_column_types: if specified column names and types will be
                                  returned alongside with result.
                                  Defaults to ``False``.
        :param external_tables: external tables to send.
                                Defaults to ``None`` (no external tables).
        :param query_id: the query identifier. If no query id specified
                         ClickHouse server will generate it.
        :param settings: dictionary of query settings.
                         Defaults to ``None`` (no additional settings).
        :param types_check: enables type checking of data for INSERT queries.
                            Causes additional overhead. Defaults to ``False``.
        :param columnar: if specified the result of the SELECT query will be
                         returned in column-oriented form.
                         It also allows to INSERT data in columnar form.
                         Defaults to ``False`` (row-like form).

        :return: * number of inserted rows for INSERT queries with data.
                   Returning rows count from INSERT FROM SELECT is not
                   supported.
                 * if `with_column_types=False`: `list` of `tuples` with
                   rows/columns.
                 * if `with_column_types=True`: `tuple` of 2 elements:
                    * The first element is `list` of `tuples` with
                      rows/columns.
                    * The second element information is about columns: names
                      and types.
        """
    async def execute_with_progress(
        self,
        query,
        args=None,
        with_column_types=False,
        external_tables=None,
        query_id="",
        settings=None,
        types_check=False,
        columnar=False,
    ) -> Any:
        """
        Executes SELECT query with progress information.
        See, :ref:`execute-with-progress`.

        :param query: query that will be send to server.
        :param args: substitution parameters for SELECT queries and data for
                       INSERT queries. Data for INSERT can be `list`, `tuple`
                       or :data:`~types.GeneratorType`.
                       Defaults to ``None`` (no parameters  or data).
        :param with_column_types: if specified column names and types will be
                                  returned alongside with result.
                                  Defaults to ``False``.
        :param external_tables: external tables to send.
                                Defaults to ``None`` (no external tables).
        :param query_id: the query identifier. If no query id specified
                         ClickHouse server will generate it.
        :param settings: dictionary of query settings.
                         Defaults to ``None`` (no additional settings).
        :param types_check: enables type checking of data for INSERT queries.
                            Causes additional overhead. Defaults to ``False``.
        :param columnar: if specified the result will be returned in
                         column-oriented form.
                         Defaults to ``False`` (row-like form).
        :return: :ref:`progress-query-result` proxy.
        """
    async def process_ordinary_query_with_progress(
        self,
        query,
        params=None,
        with_column_types=False,
        external_tables=None,
        query_id: str | None = None,
        types_check=False,
        columnar=False,
    ): ...
    def make_query_settings(self, settings): ...
    async def check_query_execution(self): ...
    async def force_connect(self): ...
    async def process_ordinary_query(
        self,
        query,
        params=None,
        with_column_types=False,
        external_tables=None,
        query_id: str | None = None,
        types_check=False,
        columnar=False,
    ): ...
    async def send_external_tables(self, tables, types_check=False): ...
    async def send_block(self, block, table_name=""): ...
    @staticmethod
    def substitute_params(query, params) -> str: ...
    async def process_insert_query(
        self,
        query_without_data,
        data,
        external_tables=None,
        query_id=None,
        types_check=False,
        columnar=False,
    ): ...
    async def receive_sample_block(self): ...
    async def send_data(self, sample_block, data, types_check=False, columnar=False): ...
    async def iter_process_ordinary_query(
        self,
        query,
        params=None,
        with_column_types=False,
        external_tables=None,
        query_id: str | None = None,
        types_check=False,
    ): ...
    def iter_receive_result(self, with_column_types=False): ...
    def track_current_database(self, query): ...
    async def execute_iter(
        self,
        query,
        args=None,
        with_column_types=False,
        external_tables=None,
        query_id="",
        settings=None,
        types_check=False,
    ) -> Any:
        """
        *New in version 0.0.14.*

        Executes SELECT query with results streaming. See, :ref:`execute-iter`.

        :param query: query that will be send to server.
        :param args: substitution parameters for SELECT queries and data for
                       INSERT queries. Data for INSERT can be `list`, `tuple`
                       or :data:`~types.GeneratorType`.
                       Defaults to ``None`` (no parameters  or data).
        :param with_column_types: if specified column names and types will be
                                  returned alongside with result.
                                  Defaults to ``False``.
        :param external_tables: external tables to send.
                                Defaults to ``None`` (no external tables).
        :param query_id: the query identifier. If no query id specified
                         ClickHouse server will generate it.
        :param settings: dictionary of query settings.
                         Defaults to ``None`` (no additional settings).
        :param types_check: enables type checking of data for INSERT queries.
                            Causes additional overhead. Defaults to ``False``.
        :return: :ref:`iter-query-result` proxy.
        """

def get_default_port(secure=False):
    """Return the port a ClickHouse server listens on by default."""
